### ISSUE TITLE
Step files?

### ISSUE THREAD

**Issue by sebastian-stumpf** [juhakaup/keyboards#10]
Hi there! Amazing project! I've printed a case and the layout feels fantastic!

I was wondering if you could add some step files to the repo. I'm trying to add a battery holder for the wireless 3x5 unicol version, but working with the stl files is a bit bothersome and I don't have a machine that can run Fusion. 

And many thanks for opensourcing your work!

**Comment by juhakaup** [comment]
I've added the files to the requests folder.

**Comment by sebastian-stumpf** [comment]
Many thanks! This is much appreciated! :slightly_smiling_face:
