### ISSUE TITLE
Any chance for a 4x6?

### ISSUE THREAD

**Issue by shensmobile** [juhakaup/keyboards#12]
I know it might ruin the design language of the board, but is there any chance you might consider making a version of this board with a numrow? I’m one of those ergo enjoyers that prefers a little bit less minimalism.

**Comment by hailee0710** [comment]
Thumbs up for this, I really love to see the 4x6 version, can't live with the numrow

**Comment by juhakaup** [comment]
![Screenshot 2024-08-07 at 19 59 36](https://github.com/user-attachments/assets/85cedabd-861e-4e7f-a418-f6e4075c711d)
![Screenshot 2024-08-07 at 20 03 45](https://github.com/user-attachments/assets/01badaa1-da34-4962-a6cd-2aa3aabf4dad)

Here's a sneak peek.

**Comment by hailee0710** [comment]
wow, fabulous!
![image](https://github.com/user-attachments/assets/c160f4bb-9c54-4542-9936-c3bda73f5f4f)

**Comment by marioolofo** [comment]
Very nice @juhakaup 
Can you share the model to print?

**Comment by shensmobile** [comment]
Absolutely fantastic.  I can't wait to print it :D

**Comment by juhakaup** [comment]
4x6 is released.
