### ISSUE TITLE
Version with two thumb keys per half?

### ISSUE THREAD

**Issue by franco-g-s** [juhakaup/keyboards#13]
The keyboard is absolutely beautiful, but it has two too many keys for me. A 5x3 layout with two thumb keys is quite popular in the community (think ferris sweep), and I think it would be great to see a Cyngus in this layout!

**Comment by juhakaup** [comment]
Removing keys isn't too hard. There is a version with two thumb keys in the 'requests and other experiments' -folder.

**Comment by franco-g-s** [comment]
Thanks! Would I need to wire it differently or make any changes to the firmware since it has one key less on each side?

**Comment by juhakaup** [comment]
You can just ignore the missing key in the wiring and the firmware.
I think I'm running a  6 column firmware despite having only 5.
