### ISSUE TITLE
controller clamp mirrored thread is left-handed

### ISSUE THREAD

**Issue by georgewild42** [juhakaup/keyboards#16]
When mirroring the controller clamp in slicer, the thread becomes left-handed. Am I missing something here?

![image](https://github.com/juhakaup/keyboards/assets/114286070/7048753b-f1f4-49ee-8121-2c96dfb657c4)

I would fix this myself by making the thread left-handed before mirroring, however I can't find the supermini wireless bracket in the Fusion file.

Thank you for this design, it's great. I am looking forward to building the wireless 3x6 as my first ergo.

**Comment by juhakaup** [comment]
Yes this is an clear oversight on my behalf. In practice, the resolution of the 3d printed m3 thread is not that great, so it doesn't really affect the performance.

**Comment by georgewild42** [comment]
Yeah, you are right it doesn't really matter. For anyone else with OCD however, I edited the STL file for the supermini wireless:

[controller_holder_supermini_wireless v1 LEFT HANDED.zip](https://github.com/juhakaup/keyboards/files/15051466/controller_holder_supermini_wireless.v1.LEFT.HANDED.zip)
