### ISSUE TITLE
3x6 version

### ISSUE THREAD

**Issue by brneor** [juhakaup/keyboards#2]
Is there a 3x6 version planned? Also, are you open for comissions?

**Comment by juhakaup** [comment]
Yes, I plan to make a 3x6 version. Hopefully I'll have time to release it later this year.
I can do comission work. I live in Europe, so postal costs may be quite high for other regions.

**Comment by brneor** [comment]
Ty for your attention! I will eagerly wait for the 3x6 version. As for the comission question, I was thinking about this 3x6 model if you were not plannig to do it.

**Comment by brneor** [comment]
Closing because of [1.0 release](https://github.com/juhakaup/keyboards/tree/main/Cygnus%20v1.0/stl/cygnus%203x6)
