### ISSUE TITLE
Build guide please

### ISSUE THREAD

**Issue by tangbonze** [juhakaup/keyboards#3]
Hello there:
I am new to custom build Keeb. Your design really impressed me. 
I can handle soldering but not sure the wire lines. Could you please kindly create a build guide or open the case and take a whole picture? 
Thanks in advanced.

**Comment by brneor** [comment]
+1 for some pics of the interior to help us see how you managed to fit the internals. It would be great!

**Comment by evantravers** [comment]
I feel like the guide he has with the v1.0 is pretty doggone good: https://github.com/juhakaup/keyboards/tree/main/Cygnus%20v1.0

Maybe this is closed?
