### ISSUE TITLE
How to open/edit in Fusion?

### ISSUE THREAD

**Issue by 222Phoenix** [juhakaup/keyboards#42]
I'm not able to open any of the .f3z files, any ideas? I tried all three, but get this error:

Error: Fusion 360 could not open cygnus_3x6.f3z because it is not a supported file type.

**Comment by juhakaup** [comment]
Can't open it directly. You need to use the upload feature to open it.
https://forums.autodesk.com/t5/fusion-design-validate-document/opening-a-f3z-file/td-p/6391844

**Comment by 222Phoenix** [comment]
Thanks. I definitely tried that also. I click data panel, then upload, choose the file, and upload, but nothing happens.

**Comment by juhakaup** [comment]
You might need to create a project first and then select it as location in the upload menu.

**Comment by 222Phoenix** [comment]
I finally figured this out. I don't get why this makes a difference but it does: on the file, you cannot just right click the file and choose "save as." You must click the "Download raw file" button.
