### ISSUE TITLE
Which controller bracket for the NRF52840

### ISSUE THREAD

**Issue by eugenenelou** [juhakaup/keyboards#44]
Hello, I'm using the NRF52840 wireless controller listed in the parts. Which controller bracket can I use ? the board is 18x33mm and the existing brackets all seem to be shorter than this.

**Comment by juhakaup** [comment]
The one in the wireless folder.

**Comment by eugenenelou** [comment]
Oh thanks, I had missed it.

**Comment by juhakaup** [comment]
I decided to move the files around a bit. All the brackets are now in the same diectory.
