### ISSUE TITLE
Choc switch version

### ISSUE THREAD

**Issue by johnlamb** [juhakaup/keyboards#6]
Any chance for a version supporting choc (V1) switches? The PCBs already has holder for the choc hot swap sockets and would be great to have the stl files for this.
Have tried adjusting the Fusion files myself but not up to speed with Fusion.

**Comment by juhakaup** [comment]
I have actually tried putting choc switches to the case. Unfortunately the problem for adding support seems to be the height of the switches and shorter travel distance. For example the switches sit so deep in the thumb cluster, that you can't really press them. Also the short travel distance means that the switches need to sit quite proud. 
So maybe the design could be altered to support the switches, but it's not really a priority for me at the moment.

I do enjoy using choc switches, but I'm planning to do different design for them.

**Comment by johnlamb** [comment]
Cheers, makes sense. Same for me when I design choc keyboards, hard to adjust to mx switches due to thin walls etc.

**Comment by johnlamb** [comment]
Cheers, makes sense. Same for me when I design choc keyboards, hard to adjust to mx switches due to thin walls etc.
