### ISSUE TITLE
unicol5 stl strange structure

### ISSUE THREAD

**Issue by AndyChiu** [juhakaup/keyboards#7]
![Screenshot_20240302-104829](https://github.com/juhakaup/keyboards/assets/1038943/df5fdf35-613d-40a9-a734-ec2d33e80ba3)
I found that the unicol5 model has a strange structure in the new STL file.

**Comment by juhakaup** [comment]
That's a good catch, thank you. I removed the chard and did some touch-ups on the underside as well.
